---
# Centralized external secrets for all applications
# These ExternalSecrets reference the password generators and create Kubernetes secrets

# OpenFGA Database Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openfga-db-credentials
  namespace: share-app
spec:
  refreshInterval: "0"  # Generate once, don't refresh
  secretStoreRef:
    name: password-store
    kind: ClusterSecretStore
  target:
    name: postgres-openfga-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: openfga_user
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: openfga-db-password

---
# OpenFGA Database URI
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openfga-db-uri
  namespace: share-app
spec:
  refreshInterval: "0"  # Generate once, don't refresh
  secretStoreRef:
    name: password-store
    kind: ClusterSecretStore
  target:
    name: openfga-db
    creationPolicy: Owner
    template:
      data:
        uri: "postgres://openfga_user:{{ .password }}@postgres-openfga-rw:5432/openfga?sslmode=require"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: openfga-db-password

---
# Keycloak Database Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
  namespace: share-app
spec:
  refreshInterval: "0"  # Generate once, don't refresh
  secretStoreRef:
    name: password-store
    kind: ClusterSecretStore
  target:
    name: postgres-keycloak-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: keycloak
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-db-password

---
# Keycloak Database Connection (JDBC format for Keycloak)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db
  namespace: share-app
spec:
  refreshInterval: "0"  # Generate once, don't refresh
  secretStoreRef:
    name: password-store
    kind: ClusterSecretStore
  target:
    name: keycloak-db
    creationPolicy: Owner
    template:
      data:
        url: "jdbc:postgresql://postgres-keycloak-rw:5432/keycloak"
        username: keycloak
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-db-password

---
# Keycloak Admin Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: share-app
spec:
  refreshInterval: "0"  # Generate once, don't refresh
  secretStoreRef:
    name: password-store
    kind: ClusterSecretStore
  target:
    name: keycloak-admin
    creationPolicy: Owner
    template:
      data:
        username: admin
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-admin-password

---
# API Database Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-api-credentials
  namespace: share-app
spec:
  refreshInterval: "0"  # Generate once, don't refresh
  secretStoreRef:
    name: password-store
    kind: ClusterSecretStore
  target:
    name: postgres-api-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: api_user
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: postgres-api-password
