apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openfga
spec:
  values:
    # Replica count - 1 for resource-constrained cluster
    replicaCount: 1

    # Disable playground in production
    playground:
      enabled: false

    # Resources optimized for current cluster capacity
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Enable autoscaling in production
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
