apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-openfga
  namespace: share-app
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"

  bootstrap:
    initdb:
      database: openfga
      owner: openfga_user
      secret:
        name: postgres-openfga-credentials

  storage:
    size: 5Gi
    storageClass: standard

  monitoring:
    enablePodMonitor: false

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
