apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-api
  namespace: share-app
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"

  bootstrap:
    initdb:
      database: api_db
      owner: api_user
      secret:
        name: postgres-api-credentials

  storage:
    size: 10Gi
    storageClass: standard

  monitoring:
    enablePodMonitor: false

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
