apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  values:
    # Development-specific settings
    replicas: 1

    # Hostname configuration for development
    extraEnv: |
      # Admin Console
      - name: KEYCLOAK_ADMIN
        valueFrom:
          secretKeyRef:
            name: keycloak-admin
            key: username
      - name: KEYCLOAK_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: keycloak-admin
            key: password

      # Database
      - name: KC_DB
        value: postgres
      - name: KC_DB_URL
        valueFrom:
          secretKeyRef:
            name: keycloak-db
            key: url
      - name: KC_DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: keycloak-db
            key: username
      - name: KC_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: keycloak-db
            key: password

      # Hostname (development)
      - name: KC_HOSTNAME
        value: localhost
      - name: KC_HOSTNAME_PORT
        value: "8081"
      - name: KC_HOSTNAME_STRICT
        value: "false"
      - name: KC_HOSTNAME_STRICT_HTTPS
        value: "false"

      # HTTP Settings
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KC_HTTP_PORT
        value: "8080"

      # Proxy settings
      - name: KC_PROXY
        value: edge

      # Features
      - name: KC_FEATURES
        value: persistent-user-sessions

      # Logging
      - name: KC_LOG_LEVEL
        value: info

    # Ingress for development (optional)
    ingress:
      enabled: false
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      ingressClassName: nginx
      rules:
        - host: keycloak.local
          paths:
            - path: /
              pathType: Prefix
