apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: share-app
type: Opaque
stringData:
  username: admin
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  namespace: share-app
type: Opaque
stringData:
  url: jdbc:postgresql://postgres-keycloak-rw:5432/keycloak
  username: keycloak
  password: keycloak_password
