apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: ">=0.26.1"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    # Operator configuration
    replicaCount: 1

    # Monitoring (can be enabled in production)
    monitoring:
      enabled: false

    # Service configuration
    service:
      type: ClusterIP
      port: 8080
