apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-openfga
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      effective_cache_size: "768MB"

  bootstrap:
    initdb:
      database: openfga
      owner: openfga_user

  storage:
    size: 10Gi
    storageClass: do-block-storage

  backup:
    barmanObjectStore:
      destinationPath: s3://backup-bucket/postgres-openfga
      s3Credentials:
        accessKeyId:
          name: backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
    retentionPolicy: "30d"

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"
