apiVersion: batch/v1
kind: Job
metadata:
  name: openfga-db-secret-generator
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: openfga-db-secret-generator
      restartPolicy: Never
      containers:
        - name: generate-secret
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e

              # Wait for CNPG credentials to be available
              echo "Waiting for CNPG credentials secret..."
              while ! kubectl get secret postgres-openfga-credentials -n openfga; do
                echo "Waiting for postgres-openfga-credentials secret..."
                sleep 2
              done

              # Get credentials from CNPG secret
              USERNAME=$(kubectl get secret postgres-openfga-credentials -n openfga -o jsonpath='{.data.username}' | base64 -d)
              PASSWORD=$(kubectl get secret postgres-openfga-credentials -n openfga -o jsonpath='{.data.password}' | base64 -d)

              # URL encode the password
              PASSWORD_ENCODED=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$PASSWORD''', safe=''))")

              # Create the URI
              URI="postgres://${USERNAME}:${PASSWORD_ENCODED}@postgres-openfga-rw:5432/openfga?sslmode=require"

              # Create the openfga-db secret
              kubectl create secret generic openfga-db \
                --from-literal=uri="${URI}" \
                --namespace=openfga \
                --dry-run=client -o yaml | kubectl apply -f -

              echo "Secret openfga-db created successfully"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfga-db-secret-generator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openfga-db-secret-generator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfga-db-secret-generator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openfga-db-secret-generator
subjects:
  - kind: ServiceAccount
    name: openfga-db-secret-generator
