apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: openfga-db-password
  namespace: share-app
spec:
  length: 32
  digits: 10
  symbols: 5
  symbolCharacters: "!@#$%^&*()_+-=[]{}|"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openfga-db-credentials
  namespace: share-app
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: password-store
    kind: ClusterSecretStore

  target:
    name: postgres-openfga-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: openfga_user
        password: "{{ .password }}"

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: openfga-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openfga-db-uri
  namespace: share-app
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: password-store
    kind: ClusterSecretStore

  target:
    name: openfga-db
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        uri: "postgres://openfga_user:{{ .password }}@postgres-openfga-rw:5432/openfga?sslmode=require"

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: openfga-db-password