apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openfga-db-credentials
  namespace: share-app
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: password-store
    kind: ClusterSecretStore

  target:
    name: postgres-openfga-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: openfga_user
        password: "{{ .password }}"

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: openfga-db-password
