apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openfga-db-uri
  namespace: share-app
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: password-store
    kind: ClusterSecretStore

  target:
    name: openfga-db
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        uri: "postgres://openfga_user:{{ .password }}@postgres-openfga-rw:5432/openfga?sslmode=require"

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: openfga-db-password
