apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: keycloak-admin-password
  namespace: share-app
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "!@#$%^&*()_+-=[]{}|"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: share-app
spec:
  refreshInterval: "0"  # Only generate once
  target:
    name: keycloak-admin
    creationPolicy: Owner
    template:
      data:
        username: admin
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-admin-password
