apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 30m
  targetNamespace: keycloak
  chart:
    spec:
      chart: keycloakx
      version: ">=7.1.0"
      sourceRef:
        kind: HelmRepository
        name: codecentric
      interval: 12h
  install:
    createNamespace: true
  values:
    # Keycloak image
    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.3.5"

    # Replica count
    replicas: 1

    # Command arguments
    command:
      - "/opt/keycloak/bin/kc.sh"
    args:
      - "start"
      - "--import-realm"
      - "--health-enabled=true"
      - "--metrics-enabled=true"

    # Extra environment variables
    extraEnv: |
      # Admin Console
      - name: KEYCLOAK_ADMIN
        valueFrom:
          secretKeyRef:
            name: keycloak-admin
            key: username
      - name: KEYCLOAK_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: keycloak-admin
            key: password

      # Database
      - name: KC_DB
        value: postgres
      - name: KC_DB_URL
        valueFrom:
          secretKeyRef:
            name: postgres-keycloak-app
            key: jdbc-uri
      - name: KC_DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: postgres-keycloak-app
            key: username
      - name: KC_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-keycloak-app
            key: password

      # HTTP Settings
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KC_HTTP_PORT
        value: "8080"

      # Proxy settings
      - name: KC_PROXY
        value: edge

      # Features
      - name: KC_FEATURES
        value: persistent-user-sessions

      # Logging
      - name: KC_LOG_LEVEL
        value: info

    # Extra volumes
    extraVolumes: |
      - name: realm-import
        configMap:
          name: keycloak-realm

    # Extra volume mounts
    extraVolumeMounts: |
      - name: realm-import
        mountPath: /opt/keycloak/data/import
        readOnly: true

    # Service configuration
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

    # Ingress (disabled by default, configure in overlays)
    ingress:
      enabled: false

    # Health checks (chart expects string format)
    livenessProbe: |
      httpGet:
        path: /health/live
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 120
      timeoutSeconds: 10
      periodSeconds: 30
      failureThreshold: 5

    readinessProbe: |
      httpGet:
        path: /health/ready
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      timeoutSeconds: 10
      periodSeconds: 30
      failureThreshold: 3

    # Resources (can be overridden in overlays)
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

    # PostgreSQL (disabled, using external CNPG cluster)
    postgresql:
      enabled: false

    # Database configuration for dbchecker
    database:
      vendor: postgres
      hostname: postgres-keycloak-rw
      port: 5432
      database: keycloak
      username: keycloak
      existingSecret: keycloak-db
      existingSecretPasswordKey: password

    # Database vendor
    dbchecker:
      enabled: true
