apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: keycloak-password
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "!@#$%^&*()_+-=[]{}|"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin
spec:
  refreshInterval: "0"  # Only generate once
  target:
    name: keycloak-admin
    creationPolicy: Owner
    template:
      data:
        username: admin
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db
spec:
  refreshInterval: "0"  # Only generate once
  target:
    name: keycloak-db
    creationPolicy: Owner
    template:
      data:
        url: "jdbc:postgresql://postgres-keycloak-rw:5432/keycloak"
        username: keycloak
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-password