apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-db-secret-generator
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: keycloak-db-secret-generator
      restartPolicy: Never
      containers:
        - name: generate-secret
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e

              # Wait for CNPG credentials to be available
              echo "Waiting for CNPG credentials secret..."
              while ! kubectl get secret postgres-keycloak-credentials -n keycloak; do
                echo "Waiting for postgres-keycloak-credentials secret..."
                sleep 2
              done

              # Get credentials from CNPG secret
              USERNAME=$(kubectl get secret postgres-keycloak-credentials -n keycloak -o jsonpath='{.data.username}' | base64 -d)
              PASSWORD=$(kubectl get secret postgres-keycloak-credentials -n keycloak -o jsonpath='{.data.password}' | base64 -d)

              # URL encode the password for URI
              PASSWORD_ENCODED=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$PASSWORD''', safe=''))")

              # Create the JDBC URI
              URL="jdbc:postgresql://postgres-keycloak-rw:5432/keycloak"

              # Create the keycloak-db secret
              kubectl create secret generic keycloak-db \
                --from-literal=url="${URL}" \
                --from-literal=username="${USERNAME}" \
                --from-literal=password="${PASSWORD}" \
                --namespace=keycloak \
                --dry-run=client -o yaml | kubectl apply -f -

              echo "Secret keycloak-db created successfully"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-db-secret-generator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-db-secret-generator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-db-secret-generator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-db-secret-generator
subjects:
  - kind: ServiceAccount
    name: keycloak-db-secret-generator
