apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  targetNamespace: external-secrets-system
  chart:
    spec:
      chart: external-secrets
      version: ">=0.20.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 12h
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # Install CRDs
    installCRDs: true

    # Replicas
    replicaCount: 1

    # Resources
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # Webhook
    webhook:
      create: true
      replicaCount: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi

    # Cert Controller
    certController:
      create: true
      replicaCount: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
