---
apiVersion: v1
kind: Service
metadata:
  name: traefik-loadbalancer
  namespace: traefik
  annotations:
    # DigitalOcean LoadBalancer configuration
    service.beta.kubernetes.io/do-loadbalancer-name: "traefik-lb"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-health-check-path: "/ping"
    service.beta.kubernetes.io/do-loadbalancer-health-check-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck: "true"
    # Enable PROXY protocol for real client IP
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-traefik-traefik
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
    - name: websecure
      port: 443
      targetPort: websecure
      protocol: TCP
